---
- name: Deploy KeyPair
  connection: local
  hosts: localhost

  vars:
    ansible_private_key: "private_key"
    ansible_public_key: "public_key"

  tasks:
    - name: Create the private key file
      blockinfile: dest=~/.ssh/id_rsa block="{{ ansible_private_key }}" create=yes
    - name: Create the public key file
      blockinfile: dest=~/.ssh/id_rsa.pub block="{{ ansible_public_key }}" create=yes
    - authorized_key: user=root key="{{ ansible_public_key }}"
    - file: path=~/.ssh/id_rsa mode=0600
    - file: path=~/.ssh/id_rsa.pub mode=0600
